# Generated by Django 4.1.3 on 2022-11-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('user_email', models.EmailField(help_text='user_email', max_length=50)),
                ('user_password', models.CharField(help_text='user_password', max_length=50)),
                ('user_contact', models.CharField(help_text='user_contact', max_length=50)),
                ('user_address', models.CharField(help_text='user_address', max_length=500)),
                ('user_dob', models.DateField(help_text='user_dob', max_length=50)),
                ('user_type', models.CharField(help_text='user_type', max_length=50)),
                ('user_image', models.ImageField(upload_to='media/')),
                ('user_qualification', models.CharField(help_text='user_qualification', max_length=100)),
            ],
            options={
                'db_table': 'user_complete_details',
            },
        ),
    ]
