# Generated by Django 4.1.3 on 2022-11-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(help_text='rating3', max_length=200, null=True)),
                ('text', models.CharField(help_text='text', max_length=200, null=True)),
                ('sentiment', models.CharField(help_text='sentiment', max_length=700, null=True)),
                ('userfeedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userfeedback', to='userapp.usermodel')),
            ],
            options={
                'db_table': 'user_feedback',
            },
        ),
    ]
