# Generated by Django 4.1.3 on 2022-11-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userfeedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_status',
            field=models.CharField(help_text='user_status', max_length=50, null=True),
        ),
    ]
