# Generated by Django 4.1.3 on 2022-11-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_usermodel_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_status',
            field=models.CharField(default='pending', help_text='user_status', max_length=50, null=True),
        ),
    ]
